// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7dyZqu2lnyzftZFUyXvRXPBPFnG5OQo',
    appId: '1:957598829443:web:035efadc38ae7b33da84b6',
    messagingSenderId: '957598829443',
    projectId: 'flash-cart-c8c13',
    authDomain: 'flash-cart-c8c13.firebaseapp.com',
    storageBucket: 'flash-cart-c8c13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAsWyGdnWqKLHK2i13cyG3EDd87Yx-wYs',
    appId: '1:957598829443:android:5f922f461772d6deda84b6',
    messagingSenderId: '957598829443',
    projectId: 'flash-cart-c8c13',
    storageBucket: 'flash-cart-c8c13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgpPbOooh16MjxvmS34PhbB_Zm7HUlVCA',
    appId: '1:957598829443:ios:a44888d3f6936496da84b6',
    messagingSenderId: '957598829443',
    projectId: 'flash-cart-c8c13',
    storageBucket: 'flash-cart-c8c13.appspot.com',
    iosBundleId: 'com.example.flashCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgpPbOooh16MjxvmS34PhbB_Zm7HUlVCA',
    appId: '1:957598829443:ios:a44888d3f6936496da84b6',
    messagingSenderId: '957598829443',
    projectId: 'flash-cart-c8c13',
    storageBucket: 'flash-cart-c8c13.appspot.com',
    iosBundleId: 'com.example.flashCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa7dyZqu2lnyzftZFUyXvRXPBPFnG5OQo',
    appId: '1:957598829443:web:ae6c38ae7ce27eebda84b6',
    messagingSenderId: '957598829443',
    projectId: 'flash-cart-c8c13',
    authDomain: 'flash-cart-c8c13.firebaseapp.com',
    storageBucket: 'flash-cart-c8c13.appspot.com',
  );

}